version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Allow immediate security updates
    open-pull-requests-limit: 5

  # Root npm dependencies (Rush configuration)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      rush-stack:
        patterns:
          - "@microsoft/rush*"
          - "@rushstack/*"
        update-types:
          - "minor"
          - "patch"

  # Main fluentui-compat package
  - package-ecosystem: "npm"
    directory: "/packages/fluentui-compat"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    labels:
      - "dependencies"
      - "npm"
      - "fluentui-compat"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      fluentui:
        patterns:
          - "@fluentui/*"
        update-types:
          - "minor"
          - "patch"
      microsoft-tools:
        patterns:
          - "@microsoft/*"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"

  # Webpack plugin package
  - package-ecosystem: "npm"
    directory: "/packages/fluentui-compat-webpack-plugin"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    labels:
      - "dependencies"
      - "npm"
      - "webpack-plugin"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - "@babel/*"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "jest*"
          - "ts-jest"
          - "jest-junit"
        update-types:
          - "minor"
          - "patch"
      webpack:
        patterns:
          - "webpack*"
          - "@types/webpack"
        update-types:
          - "minor"
          - "patch"