name: Dependabot Lockfile Update

on:
  pull_request:
    types: [opened, synchronize]

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lockfile:
    name: Update Lockfile for Dependabot PRs
    # Only run for dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20

      - name: Git config user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check if lockfile needs update
        id: check-lockfile
        run: |
          # Try to run rush install to see if lockfile is out of date
          # Rush will exit with code 1 and show specific error message if shrinkwrap is out of date
          if output=$(node common/scripts/install-run-rush.js install 2>&1); then
            echo "needs_update=false" >> $GITHUB_OUTPUT
            echo "Rush install succeeded - lockfile is up to date"
          else
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "Rush install failed - checking if it's due to out-of-date lockfile"
            echo "$output" | grep -q "shrinkwrap file.*is out of date\|do not match the current shrinkwrap" || {
              echo "ERROR: Rush install failed for reasons other than out-of-date lockfile:"
              echo "$output"
              exit 1
            }
            echo "Confirmed: lockfile needs update"
          fi

      - name: Update lockfile
        if: steps.check-lockfile.outputs.needs_update == 'true'
        run: |
          echo "Updating shrinkwrap file..."
          if ! node common/scripts/install-run-rush.js update; then
            echo "ERROR: Rush update failed"
            exit 1
          fi
          echo "Rush update completed successfully"

      - name: Check for changes
        if: steps.check-lockfile.outputs.needs_update == 'true'
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit lockfile changes
        if: steps.check-lockfile.outputs.needs_update == 'true' && steps.check-changes.outputs.has_changes == 'true'
        run: |
          echo "Committing lockfile changes..."
          # Add all pnpm lockfiles that may have been updated
          git add common/config/rush/pnpm-lock.yaml packages/fluentui-compat-webpack-plugin/pnpm-lock.yaml

          # Check if anything was actually staged
          if git diff --staged --quiet; then
            echo "No lockfile changes to commit"
            exit 0
          fi

          git commit -m "chore: update pnpm lockfile for dependabot changes"
          git push
          echo "Successfully committed and pushed lockfile changes"
